---
- name: Install jq
  yum:
    name: jq
    state: present

- name: Install wget
  yum:
    name: wget
    state: present

- name: Install tar
  yum:
    name: tar
    state: present

- name: Install gzip
  yum:
    name: gzip
    state: present

- name: Install firewalld
  yum:
    name: firewalld
    state: present

- name: Install sshpass
  yum:
    name: sshpass
    state: present

- name: Install python3
  yum:
    name: python3
    state: present
